#! /usr/bin/env python 
# coding: utf-8 
import serial 
ser = serial.Serial('COM3', 38400, dsrdtr = 1,timeout = 0) 
f=open('C:/output.txt', 'wb') #открываем файл для записи
while True: #бесконечный цикл
  a=ser.readline() #читаем данные с компорта построчно
  s=a.decode(encoding='cp1251') #меняем кодировку на читабельную
  f.write(bytes(s)) #пишем в файл
  print (s) #выводим на экран
ser.close() 
f.close()
